version: '3.8'
services:
    api:
        build: back-end/
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 8080
        ports:
            - "8080:8080" # the port number is for dev only prud port is == 8080
        restart: on-failure

    postgres:
        image: postgres:10.4
        ports:
            - "8077:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
